apiVersion: v1
kind: Service
metadata:
  name: nma-service
spec:
  type: NodePort
  selector:
    app: nma-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080  # Port externe sur le nœud
